#! /bin/bash

cd $(dirname $0)

PREFIX=

[ -f .config ] && . .config

default_PREFIX="$HOME/images"

if [ -z "$PREFIX" ]; then
    read -e -i "$default_PREFIX" -p "Install dir: " PREFIX
    PREFIX=${PREFIX%/};
    echo "PREFIX='$PREFIX'" >> .config
fi

shopt -s nullglob

for script in *-update; do
    target="$PREFIX/${script//-/\/}"
    echo "Installing $script to $target"
    install -D "$script" "$target"
done

for script in update*; do
    case "$script" in
	*~)
	    :
	    ;;
	*)
	    target="$PREFIX/$script"
	    echo "Installing $script to $target"
	    install -D "$script" "$target"
	    ;;
    esac
done
