#! /bin/bash

cd $(dirname $0)

find . -mindepth 2 -type f -name update | while read script; do
    if [ -x "$script" ]; then
	(
	    cd "$(dirname "$script")" || continue
	    echo "Running '$script'"
	    ./update "$@"
	)
    fi
done
